dist: trusty
services: docker
branches:
  only:
  - master
script: 
  - wget https://github.com/polytechnic-templates/xelatex-docker/raw/master/latexdockercmd.sh -O latexdockercmd.sh
  - wget https://github.com/polytechnic-templates/xelatex-docker/raw/master/.latexmkrc -O .latexmkrc
  - chmod a+x latexdockercmd.sh
  - ./latexdockercmd.sh latexmk -cd -f -interaction=nonstopmode -pdf main.tex
  - mv main.pdf presentation-template.pdf
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "presentation-template.pdf"
  skip_cleanup: true
  on:
    tags: true
